### ISSUE TITLE
Create presence device for larger area - Not working

### ISSUE THREAD

**Issue by prussell69** [MikeBishop/hubitat-teslamate#3]
First, Great add-on for Hubitat. Everything works perfectly, except the "Create presence device for larger area" seletion.
When I select this in the Teslamate MQTT settings, it creates a child device with my car's name, followed by "nearby".
The problem isn't the creation of the device, but the fact it never changes state. When I leave my home (geo-fence), the presence state changes on the vehicle's presence will show "not present", but the "Nearby" device still shows "present". I drive away from the house > 20 miles, and still no change. When I get back to the house and my Teslamate system changes back to "Home", the vehicle device will change to "present" in hubitat, and the "Nearby" device still doesn't change at all.
I tried to turn off the feature and allow it to remove the device, then turn the feature back on so it can re-create it (it does), but it still doesn't change state when I leave the area.
I don't know how far away the "nearby" device needs to be before it changes to "not present", but it appears to be more than 40 miles.
I was hoping it would trigger outside of the "Home" geo-fence by a set distance (say 1/2 mile) so it could be used to turn the A/C setting when getting close to home to allow time to cool/heat before getting there. Since my geo-fence for "Home" is set for a 460 feet radius, I'm literally in the driveway when the geo-fence is triggered. I don't want to increase the radius of the geo-fence because I sometimes pass by the the house travelling from one town to the next, and the main road is only 800 feet from the house, and I don't want to trigger "coming home" routines when I'm only passing by. It would be great if the size of "Nearby" was selectable.

Please let me know if I'm doing something wrong, or expecting something that isn't going to happen. If you need more info, don't be afraid to ask, I'm more than happy to help.

**Comment by MikeBishop** [comment]
No worries!  The radius is 80 miles (130 km, actually), so it's expected that a 40-mile distance would still show as nearby.  I selected that as the furthest that someone might reasonably travel in an hour, e.g. the house can assume someone will not be returning home in the near future and "go idle" to a greater degree than it might while briefly unoccupied.

Making that radius configurable seems like a simple enough feature request, though. I'll take a look.

**Comment by MikeBishop** [comment]
#4 adds this as an option. I think I covered the cases where it affects re-check frequency as well. Give it a try, and if we're both happy after a few days, I'll merge it.
